### ISSUE TITLE
GitHub improvement links

### ISSUE THREAD

**Issue by s00ly** [adwatbitcoin/adwat_bitcoin#2]
**Background**
GitHub improvement link [ساعدنا في تحسين هذا المحتوى] is a great tool across the website.

**Issue**
improvement link [ساعدنا في تحسين هذا المحتوى] is not present on the landing page.

**Suggestion**
To add it

**Comment by adwatbitcoin** [comment]
Thanks @s00ly 
"Repo Edit Link" is a plugin to "[Vuepress](https://vuepress.vuejs.org/)". There is no option to add "edit link" on the main Page.

You can still submit PR to edit texts directly from here:
https://github.com/adwatbitcoin/adwat_bitcoin/tree/main/docs/README.md
